export const pricingPlans = [
    {
        title: 'freelancer',
        price: '20',
        upfront: '80',
        currency: 'AUD',
        frequency: '/month',
        description: 'The essentials to provide your best work for clients.',
        features: [
            '5 pages',
            'SEO',
            '24 hour support response time',
        ],
        cta: 'start your trial',
        mostPopular: false,
    },
    {
        title: 'advanced',
        price: '35',
        upfront: '120',
        currency: 'AUD',
        frequency: '/month',
        description: 'The essentials to provide your best work for clients.',
        features: [
            '5 pages',
            'SEO',
            '24 hour support response time',
            '5 pages',
            'SEO',
            '24 hour support response time',
        ],
        cta: 'start your trial',
        mostPopular: true,
    },
    {
        title: 'enterprise',
        price: '100+',
        upfront: '80',
        currency: 'AUD',
        frequency: '/month',
        description: 'The essentials to provide your best work for clients.',
        features: [
            '5 pages',
            'SEO',
            '24 hour support response time',
            '5 pages',
            'SEO',
            '24 hour support response time',
            '5 pages',
            'SEO',
            '24 hour support response time',
        ],
        cta: 'start your trial',
        mostPopular: false,
    },
]