export const pricingPlans = [
    {
        title: 'UI/UX Design',
        price: '20',
        upfront: '80',
        currency: 'AUD',
        frequency: '/month',
        description: 'One Page. Tiny price. All yours.',
        features: [
            '2 pages',
            'SEO',
            '24 hour support response time',
        ],
        cta: 'start your trial',
        mostPopular: false,
    },
    {
        title: 'Website Development',
        price: '35',
        upfront: '120',
        currency: 'AUD',
        frequency: '/month',
        description: 'The popular choice.',
        features: [
            'Up to 8 pages',
            'SEO',
            '24 hour support response time',
            '5 pages',
            'SEO',
            '24 hour support response time',
        ],
        cta: 'start your trial',
        mostPopular: true,
    },
    {
        title: 'Website Management',
        price: '100+',
        upfront: '80',
        currency: 'AUD',
        frequency: '/month',
        description: 'The essentials to provide your best work for clients.',
        features: [
            '5 pages',
            'SEO',
            '24 hour support response time',
            '5 pages',
            'SEO',
            '24 hour support response time',
            '5 pages',
            'SEO',
            '24 hour support response time',
        ],
        cta: 'start your trial',
        mostPopular: false,
    },
]